import Head from 'next/head'
import Image from 'next/image'
import Hub from '../components/Hub.js'
import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Bible Recall</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Bible Recall
        </h1>
        <Hub/>
      </main>
      {/* <footer className={styles.footer}>
      </footer> */}
    </div>
  )
}
